CREATE TABLE IF NOT EXISTS case_reminder_triggers (
  id UUID PRIMARY KEY,
  reminder_id UUID NOT NULL REFERENCES case_reminders(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel TEXT NOT NULL DEFAULT 'in_app',
  trigger_at TIMESTAMPTZ NOT NULL,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE case_reminders
  ADD COLUMN IF NOT EXISTS case_number TEXT,
  ADD COLUMN IF NOT EXISTS court TEXT,
  ADD COLUMN IF NOT EXISTS remind_offsets_minutes INT[],
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

